# Generated by Django 5.1.4 on 2024-12-16 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_genre_by', to='books.bookgenre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_genre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book_genre')},
            },
        ),
    ]
