# Generated by Django 5.1.4 on 2024-12-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_favoritegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteGenre',
        ),
    ]
